title: Alexander Bravo # your name (or website title) here
logo: "/images/AvatarMaker.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This porfolio is created for my web design class.
  <br><br>
 I hope you enjoy my porfolio and please contact me if you would like.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
